# Matrix controller sample configuration

# How to connect to RabbitMQ
rabbitmq_host: localhost
rabbitmq_port: 5672
rabbitmq_username: user
rabbitmq_password: user
event_exchange: events


# Names of the nodes that the controller will run on.
# These need not be real hostnames.
sim_nodes:
    - node1
    - node2

# The TCP port the controllers should listen to
# for incoming connections agent connections
controller_port:
    node1: 16001
    node2: 16002

# The number of agent processes
# that will run on each host
num_agentprocs:
    node1: 1
    node2: 1

# The data store location
# Environment variables can be used here
state_dsn:
    node1: $HOME/data/matrix_sims/events1.db
    node2: $HOME/data/matrix_sims/events2.db

# The root seed
root_seed: 42

# The state module to be used
# for updating the event store
state_store_module: matrix.dummystore

# Number of rounds to run the simulation for
num_rounds: 10

# Starting time of the simulation
start_time: 2017-08-17

# The time a single round represents
round_time: 1h
